;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;Soma.asm - soma de dois numeros em hexadecimal COM CARRY
;Prof. Fernando M. de Azevedo - 15.03.2005
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ORG 2000H
	LXI SP,23FFH	; CARREGA O SP COM O VALOR 23FF
	LXI B,0000H	; CARREGA O PAR B,C COM O VALOR 0000
	PUSH PSW	; SALVA O PSW
	PUSH B		; SALVA O PAR B,C
	XRA A		; ZERA O ACUMULADOR E OS FLAGS
	LDA 2020H	; CARREGA NO ACUMULADOR O CONTEUDO DE 2020H
	MOV B,A		; MOVE O CONTEUDO DO ACUMULADOR PARA B
	LDA 2021H	; CARREGA NO ACUMULADOR O CONTEUDO DE 2021H
	ADD B		; SOMA O A COM B COLOCANDO O RESULTADO EM A
	STA 2023H	; ARMAZENA NA POSICAO DE MEMORIA 2023H
	JNC X1		; TESTA O FLAG CARRY PAARA VER SE TEM VAI UM
	MVI A,01	; MOVE 01 PARA O ACUMULADOR
	STA 2022H	; ARMAZENA NA POSICAO DE MEMORIA 2022H
X1:	POP B		; RESTAURA O PAR B,C
	POP PSW		; RESTAURA O PSW
	HLT		; UMA MANEIRA DE FINALIZAR. nA REALIDADE ELE PARA
			; ATE QUE HAJA NOVO COMANDO	
	END