;Gustavo Simas da Silva

RESET	EQU	0h
ATRASO 	EQU 0AH
LTINT1	EQU 13H
STATE	EQU 20H
	
		ORG RESET
		JMP INICIO
		ORG	LTINT1
		JMP HANDLER
		
INICIO: MOV	IE, #10000100b ; ATIVA INTERRUPCAO 1
		SETB IT1 ;BORDA DE DESCIDA
		MOV STATE,#0FFH ;INICIALIZAÁ„O
		MOV R0,#STATE
		MOV A, #01H ;APENAS UM BIT SETADO / LED ACESO
		MOV P2, A 
		MOV R2, #00H
		
ROT_DIR: CJNE @R0,#0FFH, ROT_ESQ ;SALTO CONDICIONAL PARA ROTACAO ESQUERDA
		RR A ;ROTACIONA PARA DIREITA
		JMP REPETE

ROT_ESQ: RL A ;ROTACIONA PARA ESQUERDA
		
REPETE:	MOV P2, A
		MOV R2, A ;REGISTRA CONTEUDO ATUAL DO ACUMULADOR
		MOV A,#ATRASO
		CALL DELAY
		MOV A, R2 ;RETORNA VALOR REGISTRADO
		JMP ROT_DIR
		
DELAY: 	DJNZ ACC,DELAY ; subrotina DELAY
		RET
		
HANDLER: XRL STATE,#0FFH ;COMPLEMENTA CONTEUDO DE STATE
		RETI
		
		END
	