RESET		EQU     00H
LTSERIAL	EQU    	23H ; local tratador
STATE       EQU     20H

ORG RESET  ;PC=0 depois de reset
JMP INICIO 

ORG	LTSERIAL
JNB	TI, CLRRI
CLR TI
JMP CONTINUA
CLRRI:		CLR RI
CONTINUA:	MOV STATE,#1H
			RETI

INICIO:  	MOV IE,#10010000B
			MOV SCON,#11010000B
			MOV TMOD,#00100000B
			MOV TH1,#0FDH
			MOV TL1,#0FDH
			MOV PCON,#80H
			SETB TR1
			MOV STATE,#0H
			MOV R0,#STATE
			;MOV DPTR,#TABELA -- Exemplo
			
VOLTA3:		MOV A,#41H
		
VOLTA1:		MOV SBUF,A
			;MOV SBUF,#'M' -- Exemplo

VOLTA2:		CJNE @R0,#1,VOLTA2
			MOV STATE,#0H
			
			INC A
			CJNE A,62H,VOLTA1
			
			JMP VOLTA3
			
			
			;JMP VOLTA0
				
;TABELA: 	DB 'Microcontrolador' -- Exemplo
	
END