;MATHEUS FIGUEIREDO
RESET 	 EQU 00H
LTSERIAL EQU 23H ; local tratador
STATE 	 EQU 20H
		 ORG RESET ;PC=0 depois de reset
		 JMP INICIO
		 ORG LTSERIAL
		 CLR TI
		 MOV STATE,#1H
		 RETI
INICIO:  MOV IE,#10010000B
		 MOV SCON,#11000000B
		 MOV TMOD,#00100000B   ; C/T = 0, MODE TIMER 1 = 2,
		 MOV TH1,#0FFH		   ; RELOAD FDH
		 MOV TL1,#0FFH
		 MOV PCON,#80H          ;SMOD = 1
		 SETB TR1				;INICIA A CONTAGEM do timer 1, igual qnd configura timer
		 MOV STATE,#0H
		 MOV R0,# STATE
		SETB P
		MOV A,#41H
		MOV C,P
		MOV TB8,C
		MOV SBUF,A

VOLTA: 	 CJNE @R0,#1,VOLTA
		 MOV STATE,#0H
		
		INC A
		MOV C,P
		MOV TB8,C
		MOV SBUF,A		
		
		CJNE A,#61H,VOLTA
		
		MOV A,#40H
		JMP VOLTA


END 